(define (accumulate combiner start n term)
	(do ((sum start (combiner sum (term index))) (index 1 (+ index 1)))
		((> index n) sum) 
	)

)
(define (accumulate1 combiner start n term)
  (define (helper combiner start n term sum index)
	(if (= indedx n) (combiner sum (term index))
		(helper combiner start n term sum+(combiner sum (term index)) (+ index 1))
	 )
   )
  (helper combiner start n term start 1)
)
